Unit 3/DjangoReviewII/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
	path('', views.courses, name='courses'),
	path('<int:course_id>/', views.detail, name='detail'),
]

Unit 3/DjangoReviewII/coursesProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from courses import views
from registration import views

urlpatterns = [
    path('', views.home),
    path('courses/', include('courses.urls')),
    path('registration/', include('registration.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Unit 3/DjangoReviewII/registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
	path('', views.registration, name='registration'),
	path('details/', views.registration_details, name='registration_details'),
]

Unit 3/DjangoReviewII/courses/models.py
from django.db import models

# Create your models here.

class Courses(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='courses/images/')
    
    def __str__(self) -> str:
        return self.name
    

Unit 3/DjangoReviewII/courses/views.py
from django.shortcuts import render, get_object_or_404
from .models import Courses

# Create your views here.
def home(request):
    return render(request, 'courses/home.html')

def courses(request):
    courses = Courses.objects.all()
    return render(request, 'courses/courses.html', {'courses':courses})

def detail(request, course_id):
    course = get_object_or_404(Courses, pk=course_id)
    return render(request, 'courses/detail.html', {'course':course})

Unit 3/DjangoReviewII/courses/templates/courses/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Base</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'courses/style.css' %}" />
  </head>
  <body>
    <div class="wrapper d-flex flex-column min-vh-100">
      <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
        <div class="container-fluid">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'courses:courses' %}">Courses</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'registration:registration' %}">Registration</a>
            </li>
          </ul>
        </div>
      </nav>
      <div class="container pt-5">
        {% block content %}{% endblock %}
      </div>
      <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item">
            <a href="/" class="nav-link px-2 text-muted">Home</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'courses:courses' %}" class="nav-link px-2 text-muted">Courses</a>
          </li>
          <li class="nav-item">
            <a href="" class="nav-link px-2 text-muted">Registration</a>
          </li>
        </ul>
        <p class="text-center text-muted">&copy; 2022 Company, Inc</p>
      </footer>
    </div>
  </body>
</html>

Unit 3/DjangoReviewII/courses/templates/courses/courses.html
{% extends 'courses/base.html' %} {% load static %} {% block content %}
<div class="row">
  {% for course in courses %}
  <div class="col-lg-4 col-md-6 mb-4">
    <div class="card column align-items-center p-3 m-3">
      <h2>{{ course.name }}</h2>
      <h4>{{ course.description }}</h4>
      <img src="{{ course.image.url }}" width="250px" />
      <a href="{% url 'courses:detail' course.id %}">See more</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

Unit 3/DjangoReviewII/courses/templates/courses/detail.html
{% extends 'courses/base.html' %} {% load static %} {% block content %} 
<div class="d-flex flex-column align-items-center">
    <h1>{{ course.name }}</h2>
    <h3>{{ course.description }}</h4>
    <img src="{{ course.image.url }}" width="250px" />
</div>
{% endblock %}

Unit 3/DjangoReviewII/courses/templates/courses/home.html
{% extends 'courses/base.html' %} {% load static %} {% block content %} 
<div class="d-flex flex-column align-items-center ">
    <h2 class="mb-4">This is the home page!</h2>
    <img src="{% static 'courses/Home.jpg' %}" alt="Foto de una casa" width="200px">
</div>
{% endblock %}