Unit 4/Blog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.Index.as_view()),
    path("all-posts/",views.PostList.as_view(), name="all_posts"),
    path("<slug:slug>",views.PostDetail.as_view(), name="blog_detail"),
    path("read-later/",views.ReadLater.as_view(), name="read-later")
]

Unit 4/Blog/blog_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("blog.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Unit 4/Blog/blog/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.urls import reverse

# Create your models here.
class Tag(models.Model):
    caption = models.CharField(max_length=150)
    
    def __str__(self):
        return f"{self.caption}"

class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Post(models.Model):
    title = models.CharField(max_length=200)
    excerpt = models.CharField(max_length=200)
    imageName = models.ImageField(upload_to="posts",null=True)
    date = models.DateField(auto_now=True)
    slug = models.SlugField(default="", null=False, db_index=True)
    content = models.TextField(validators=[MinLengthValidator(10)])
    author = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL, related_name="fkauthor", blank=True)
    tag = models.ManyToManyField(Tag)
    
    def get_absolute_url(self):
        return reverse("blog:blog_detail", args=[self.slug])
    
class Comment(models.Model):
    user_name=models.CharField(max_length=120)
    user_email=models.EmailField()
    text=models.TextField(max_length=400)
    post=models.ForeignKey(Post,on_delete=models.CASCADE, related_name="comments")

Unit 4/Blog/blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model= Comment
        exclude=["post"]
        labels = {
            "user_name" : "Your name:",
            "user_email": "Your email:",
            "text": "Comment:"
        }
        

Unit 4/Blog/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.views.generic import ListView, DetailView
from .forms import CommentForm
from django.views import View
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
# def index(request):
#     posts = Post.objects.order_by("-date")[:3]
    
#     return render(request, "blog/index.html", {"posts": posts})
    
# def all_posts(request):
#     all_posts = Post.objects.all().order_by("-date")
#     return render(request, "blog/all_posts.html", {"all_posts":all_posts})

# def blog_detail(request, slug):
#     post = get_object_or_404(Post, slug=slug)
#     tags = post.tag.all()
#     return render(request, "blog/blog_detail.html", {"post":post,"tags":tags})


class Index(ListView):
    template_name = "blog/index.html"
    model = Post
    context_object_name = "posts"
    
    def get_queryset(self):
        return Post.objects.all().order_by("-date")[:3]
    
class PostList(ListView):
    template_name = "blog/all_posts.html"
    model = Post
    context_object_name = "all_posts"
    
    def get_queryset(self):
        return Post.objects.all().order_by("-date")
    
class PostDetail(View):
    # template_name = "blog/blog_detail.html"
    # model = Post
    
    def get(self,request,slug):
        post = Post.objects.get(slug=slug)
        context = {
            "post":post,
            "post_tags": post.tag.all(),
            "comment_form":CommentForm(),
            "comments": post.comments.all().order_by("-id")
        }
        return render(request, "blog/blog_detail.html",context)

    def post(self,request,slug):
        comment_form = CommentForm(request.POST)
        post = Post.objects.get(slug=slug)
        
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
            return HttpResponseRedirect(reverse("blog:blog_detail",args=[slug]))
        
        context = {
            "post":post,
            "post_tags": post.tag.all(),
            "comment_form":CommentForm()
        }
        return render(request, "blog/blog_detail.html",context)
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     tags = self.object.tags.all()
    #     context["post_tags"] = tags
    #     context["comment_form"] = CommentForm
    #     return context

class ReadLater(View):
    def get(self, request):
        stored_posts = request.session.get("stored_posts")

        context = {}
        if stored_posts is None or len(stored_posts) == 0:
            context["stored_posts"] = []
            context["has_posts"] = False
        else:
            posts = Post.objects.filter(id__in=stored_posts)
            context["posts"] = posts
            context["has_posts"] = True
            
        return render(request, "blog/stored_posts.html", context)
    def post(self, request):
        stored_posts = request.session.get("stored_posts")
        if stored_posts is None:
            stored_posts = []
        post_id = int(request.POST["post_id"])
        if post_id not in stored_posts:
            stored_posts.append(post_id)
        else:
            stored_posts.remove(post_id)
            
        request.session["stored_posts"] = stored_posts
        return HttpResponseRedirect("/")

Unit 4/Blog/blog/templates/blog/all_posts.html
{% extends "blog/base.html" %}
{% load static %} 
{% block title %} Posts {% endblock %}
{% block page_css %}
  <link rel="stylesheet" href="{% static 'blog/styles/index.css' %}" />
{% endblock %}
{% block content %}
  <img alt="Imagen blog" src="{% static 'blog/images/hero.webp' %}" width="300px"/>
  <h1>Bienvenido! Los mejores blogs.</h1>
  <div class="posts-container">
    {% for post in all_posts %}
      <div class="post">
        {% include "blog/includes/post.html" %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

Unit 4/Blog/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/styles/base.css' %}" />
    {% block page_css %}{% endblock %}
  </head>
  <body>
    <header>
      <h1>Mi Blog</h1>
      <nav>
        <a href="/">Inicio</a>
      </nav>
    </header>
    <main>
    {% block content %}{% endblock %}
    </main>
    <footer>
      <p>&copy; 2025 Mi Blog</p>
    </footer>
  </body>
</html>

Unit 4/Blog/blog/templates/blog/blog_detail.html
{% extends "blog/base.html" %} {% load static %}
{% block title %} {{ post.title }} {% endblock %}
{% block page_css %}
  <link rel="stylesheet" href="{% static 'blog/styles/details.css' %}" />
{% endblock %}
{% block content %}
    <img src="{{ post.imageName.url }}" alt="{{ post.title }}" width="300px">
    <h1>{{ post.title }} - {{ post.date|date:'d/m/Y'}}</h1>
    <h2></h2>
    <h2>Excerpt: {{ post.excerpt }}</h2>
    <h2>Author: <a href="mailto:{{ post.author.email }}">{{ post.author.first_name }} {{ post.author.last_name }}</a></h2>
    <p><h2>Content:</h2> {{ post.content }}</p>
    <h2>Tags:</h2>
    <ol>
        {% for tag in post.tag.all %}
            <li>{{ tag }}</li>
        {% endfor %}
    </ol>

    <section>
        <h3>Comments:</h3>
        <form action="{% url 'blog:blog_detail' post.slug %}" method="POST">
            {% csrf_token %}
            {% for field in comment_form %}
            <div class="form-control">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            <button type="submit">Send</button>
        </form>
    </section>
    <div id="comments">
        <ul>
        {% for comment in comments %}
            <li>{{ comment.user_name }} - {{ comment.text }}</li>
        {% endfor %}
        </ul>
    </div>
    <div id="read-later">
        <form action="{% url 'blog:read-later'%}" method="POST">
            {% csrf_token %}
            <input type="hidden" value="{{ post.id }}"  name="post_id"></input>
            <button>Read later</button>
        </form>
    </div>
{% endblock %}

Unit 4/Blog/blog/templates/blog/includes/post.html
<a href="{{ post.get_absolute_url }}">
  {{ post.title }}
  <p>{{ post.date|date:'d/m/Y' }}</p>
</a>

Unit 4/Blog/blog/templates/blog/index.html
{% extends "blog/base.html" %} {% load static %} {% block title %} Posts
{%endblock %} {% block page_css %}
<link rel="stylesheet" href="{% static 'blog/styles/index.css' %}" />
{% endblock %} {% block content %}
<img
  alt="Imagen blog"
  src="{% static 'blog/images/hero.webp' %}"
  width="300px"
/>
<h1>Bienvenido! Los mejores blogs.</h1>
<div class="posts-container">
  {% for post in posts %}
  <div class="post">{% include "blog/includes/post.html" %}</div>
  {% endfor %}
</div>
<a href="{% url 'blog:all_posts' %}">All blogs</a>
{% endblock %}

Unit 4/Blog/blog/templates/blog/stored_posts.html
{% extends "blog/base.html" %} {% load static %} {% block title %} Stored Posts
{% endblock %} {% block page_css %}
<link rel="stylesheet" href="{% static 'blog/styles/stored_posts.css' %}" />
{% endblock %} {% block content %}
<section id="stored-posts">
  <h2>Stored posts</h2>
  {% if not has_posts %}
  <p>you didn´t have posts</p>
  {% endif %}
  <ul>
    {% for post in posts %} {% include "blog/includes/post.html" %} {% endfor %}
  </ul>
</section>
{% endblock %}