Unit 3/eventManager/eventManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from events import views
from participants import views

urlpatterns = [
    path('',views.home),
    path('events/',include('events.urls')),
    path('participants/',include('participants.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Unit 3/eventManager/events/urls.py
from django.urls import path
from . import views

app_name="events"

urlpatterns = [
 path('', views.events, name='events'),
 path('<int:event_id>/', views.detail, name='detail'),
]

Unit 3/eventManager/participants/urls.py
from django.urls import path
from . import views

app_name="participants"

urlpatterns = [
 path('', views.register, name='register'),
 path('detail/', views.detail, name='detail'),
]

Unit 3/eventManager/events/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='events/images/')
    fecha = models.DateField()
    
    def __str__(self) -> str:
        return self.name

Unit 3/eventManager/participants/models.py
from django.db import models

# Create your models here.
class Participant(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    event = models.CharField(max_length=200)

Unit 3/eventManager/events/views.py
from django.shortcuts import render,get_object_or_404
from .models import Event

# Create your views here.
def home(request):
    return render(request,'events/home.html')

def events(request):
    events = Event.objects.all()
    return render(request, 'events/events.html', {'events':events})

def detail(request,event_id):
    event = get_object_or_404(Event,pk=event_id)
    return render(request, 'events/detail.html', {'event':event})

Unit 3/eventManager/participants/views.py
from django.shortcuts import render
from .models import Participant

# Create your views here.
def home(request):
    return render(request,'events/home.html')

def register(request):
    return render(request, 'participants/form.html', {'register':'register'})

def detail(request):
    name = request.GET.get('name')
    surname = request.GET.get('surname')
    age = int(request.GET.get('age'))
    event = request.GET.get('event')
    
    return render(request, 'participants/details.html', {'name':name, 'surname':surname,'age':age, 'event':event})

Unit 3/eventManager/events/templates/events/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'events/style.css' %}" />
  </head>
  <body>
    <div class="wrap">
      <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="container-fluid">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="/">EventManager</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'events:events' %}">Events</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'participants:register' %}"
                >Participants</a
              >
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <main>
      <div class="container">{% block content %}{% endblock %}</div>
    </main>

    <footer class="container text-center p-5 mt-auto">&COPY;Footer</footer>
  </body>
</html>

Unit 3/eventManager/events/templates/events/detail.html
{% extends 'events/base.html' %} {% load static %} {% block content %}
<div class="container-fluid p-5 text-center">
  <h2>{{ event.name }}</h2>
  <h4>{{ event.description }}</h4>
  <img
    src="{{ event.image.url }}"
    alt="{{ event.description }}"
    class="mb-2"
    width="300px"
  />
  <div class="card-footer" aria-disabled="true">
    {{ event.fecha|date:'j F Y' }}
  </div>
</div>
{%endblock %}

Unit 3/eventManager/events/templates/events/events.html
{% extends 'events/base.html' %} {% load static %} {% block content %}
<div class="d-flex column p-5">
  {% for event in events %}
  <a href="{% url 'events:detail' event.id %}" none>
    <div class="card row text-center p-3 m-3">
      <h2>{{ event.name }}</h2>
      <h4>{{ event.description }}</h4>
      <img
        src="{{ event.image.url }}"
        alt="{{ event.description }}"
        class="mb-2"
        width="100px"
        height="300px"
      />
      <div class="card-footer" aria-disabled="true">
        {{ event.fecha|date:'jS F Y' }}
      </div>
    </div>
  </a>
  {% endfor %}
</div>
{%endblock %}

Unit 3/eventManager/events/templates/events/home.html
{% extends 'events/base.html' %} {% load static %} {% block content %}
<section class="p-5">
  <h2 class="text-center">¿Qué es este sistema?</h2>
  <p>
    Nuestro sistema de gestión de eventos está diseñado para ayudarte a
    coordinar todos los aspectos de un evento, desde la creación de agendas y el
    manejo de inscripciones, hasta el seguimiento de asistentes y el análisis de
    resultados. Ideal para conferencias, bodas, reuniones empresariales y más.
  </p>
</section>
<section class="column text-center">
  <img
    src="{% static 'events/home.webp' %}"
    alt="Equipo organizando un evento"
    class="img-fluid"
    width="500px"
  />
</section>
{% endblock %}