Unit 5/FinalProject/library/books/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('books/', views.ListBooks.as_view(), name="books"),
    path('books/read-later/add/', views.AddReadLater.as_view(), name="addReadLater"),
    path('books/read-later/', views.ReadLaterList.as_view(), name="readLater"),
    path('books/read-later/', views.ReadLaterList.as_view(), name="readLater"),
    
    path('books/<int:pk>/', views.DetailBook.as_view(), name="detail"),
    path("books/add", views.AddBook.as_view(), name="add"),
    path("books/<int:pk>/update", views.UpdateBook.as_view(), name="update"),
    path("books/<int:pk>/delete", views.DeleteBook.as_view(), name="delete"),
    
    path('authors/',views.ListAuthors.as_view(), name='authors'),
    path("authors/<int:pk>/", views.DetailAuthor.as_view(), name="authors_detail"),
    path("authors/add", views.AddAuthor.as_view(), name="addAuthor"),
    path("authors/<int:pk>/update", views.UpdateAuthor.as_view(), name="updateAuthor"),
    path("authors/<int:pk>/delete", views.DeleteAuthor.as_view(), name="deleteAuthor"),
    
    path('search/', views.SearchView.as_view(), name='search'),
]

Unit 5/FinalProject/library/library/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from books import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Unit 5/FinalProject/library/books/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=255)
    bio = models.TextField()
    image = models.ImageField(upload_to='authors/images/',blank=True, null=True)
    readers = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])

    def __str__(self):
        return self.name
    
class Book(models.Model):
    title = models.CharField(max_length=250)
    image = models.ImageField(upload_to='books/images/', blank=True, null=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    publication_date = models.DateField()
    rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])
    authors = models.ManyToManyField(Author)

    def __str__(self):
        return self.title+f" ({self.id})"
    

Unit 5/FinalProject/library/books/forms.py
from django import forms

from .models import Author
        
class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"
        labels = {
            "name": "Author name:",
            "bio": "Author bio:",
            "image":"Author image",
            "readers":"Number of readers"
        }


    

Unit 5/FinalProject/library/books/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models  import Book, Author
from django.views.generic.base import TemplateView, View
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .forms import AuthorForm

# Book
class Home(ListView):
    template_name = "books/home.html"
    model = Book
    context_object_name = "books"
    
    def get_queryset(self):
        return Book.objects.all().order_by("-rating")[:3]

class ListBooks(ListView):
    template_name = "books/book_list.html"
    model = Book
    context_object_name = "books"

    def get_queryset(self):
        sort_by = self.request.GET.get("sort_by", "")
        books = Book.objects.all()

        if sort_by in ["price", "-price", "publication_date", "-publication_date", "rating", "-rating"]:
            books = books.order_by(sort_by)

        return books

class DetailBook(DetailView):
    template_name = "books/book_detail.html"
    model = Book
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        read_later_books = self.request.session.get("read_later", [])
        context["is_read_later"] = str(self.object.id) in read_later_books
        return context

class AddBook(CreateView):
    model = Book
    fields = "__all__"
    template_name = "books/add_book.html"
    success_url = "/books"
    
class UpdateBook(UpdateView):
    model = Book
    fields = "__all__"
    template_name = "books/update_book.html"
    success_url = "/books"

class DeleteBook(DeleteView):
    model = Book
    fields = "__all__"
    template_name = "books/delete_book.html"
    success_url = "/books"
    
class AddReadLater(View):
    def post(self, request):
        book_id = request.POST.get("book_id")
        if not book_id:
            return HttpResponseRedirect("/books")

        read_later_books = request.session.get("read_later", [])

        if book_id in read_later_books:
            read_later_books.remove(book_id)
        else:
            read_later_books.append(book_id)

        request.session["read_later"] = read_later_books
        return HttpResponseRedirect(f"/books/{book_id}") 


class ReadLaterList(View):
    def get(self, request):
        read_later_books = request.session.get("read_later", [])
        books = Book.objects.filter(id__in=read_later_books)
        return render(request, "books/read_later.html", {"books": books})


# Author    
class ListAuthors(ListView):
    template_name = "authors/author_list.html"
    model = Author
    context_object_name = "authors"
    
    def get_queryset(self):
        return Author.objects.all().order_by("-readers")

class DetailAuthor(DetailView):
    template_name = "authors/author_detail.html"
    model = Author
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["books_by_author"] = Book.objects.filter(authors=self.object)
        return context
        
class AddAuthor(CreateView):
    model = Author
    form_class = AuthorForm
    template_name = "authors/add_author.html"
    success_url = "/authors"

class UpdateAuthor(UpdateView):
    model = Author
    form_class = AuthorForm
    template_name = "authors/update_author.html"
    success_url = "/authors"
    
class DeleteAuthor(DeleteView):
    model = Author
    template_name = "authors/delete_author.html"
    success_url = "/authors"

# Barra de busquéda
class SearchView(ListView):
    template_name = "books/search.html"
    context_object_name = "books"

    def get_queryset(self):
        query = self.request.GET.get("q", "").strip()
        filter_option = self.request.GET.get("filter", "all")

        books = Book.objects.filter(title__icontains=query) if query else Book.objects.all()
        authors = Author.objects.filter(name__icontains=query) if query else Author.objects.all()

        if filter_option == "books":
            return books
        elif filter_option == "authors":
            return [] 
        return books

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get("q", "").strip()
        filter_option = self.request.GET.get("filter", "all") 

        context["query"] = query
        context["filter"] = filter_option 

        if filter_option in ["all", "authors"]:
            context["authors"] = Author.objects.filter(name__icontains=query) if query else Author.objects.all()
        else:
            context["authors"] = [] 

        return context

Unit 5/FinalProject/library/books/templates/books/add_book.html
{% extends "books/base.html" %} {% load static %}{% block content %}
<div class="container d-flex justify-content-center align-items-center text-center mt-4 mb-4">
  <div class="card shadow p-4 w-50">
    <h2 class="text-center mb-4">Add a New Book</h2>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% comment %} {% for field in form %}
        <div class="mb-3">
          {{ field.label_tag }}
          {{ field }}
          <div class="text-danger">
            {{ field.errors }}
          </div>
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary w-100">Add Book</button> {% endcomment %}
      <h3>Oh,oh! :(
        <br>
        You don't have permissions...</h3>
      <a class="btn btn-secondary w-100 mt-3" href="{% url 'book:books' %}">Cancel</a>
    </form>
  </div>
</div>
{% endblock content %}

Unit 5/FinalProject/library/books/templates/books/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Library</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      rel="icon"
      type="image/png"
      href="{% static 'books/BookLogoTransparente.png' %}"
    />
    <link rel="stylesheet" href="{% static 'books/style.css' %}" />
  </head>
  <body>
    <div class="wrapper d-flex flex-column min-vh-100">
      <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'book:home' %}">
            <img
              src="{% static 'books/BookLogoTransparente.png' %}"
              alt="Logo"
              width="30"
              height="24"
              class="d-inline-block align-text-top"
            />
            Library
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarText"
            aria-controls="navbarText"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'book:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'book:books' %}">Books</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'book:authors' %}">Authors</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'book:readLater' %}">Read Later</a>
              </li>
            </ul>
            <form method="get" action="{% url 'book:search' %}" class="mb-4">
              <div class="input-group">
                <input
                  type="text"
                  name="q"
                  class="form-control"
                  placeholder="Search for a book or author"
                  value="{{ query }}"
                />
                <button type="submit" class="btn btn-secondary">Search</button>
              </div>
            </form>
          </div>
        </div>
      </nav>

      <div class="container-fluid">{% block content %}{% endblock %}</div>

      <footer>
        <p>&copy; 2024 Library. All rights reserved.</p>
        <p>
          <a href="#">Privacy Policy</a> |
          <a href="#">Terms of Service</a>
        </p>
      </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

Unit 5/FinalProject/library/books/templates/books/book_detail.html
{% extends "books/base.html" %} {% load static %} {% block content %}
<div class="container mt-5 ">
  <div class="row">
    <div class="col-md-6">
      <img src="{% if book.image %}{{ book.image.url }}{% else %}{% static "books/default.jpg" %}{% endif %}" class="card-img-top" alt="{{ book.title }}" style="max-height: 600px; width: 400px; object-fit: cover" />
    </div>
    <div class="col-md-6">
      <h1 class="mb-3">{{ book.title }}</h1>
      <p class="text-muted">
        <strong>Published:</strong> {{ book.publication_date|date:"j F, Y" }}
      </p>
      <p class="fs-5">{{ book.description }}</p>
      <p class="fs-5">
        Written by:{% for author in book.authors.all %}
        <a href="{% url 'book:authors_detail' author.id %}"><li>{{ author.name }}</li></a>
        {% endfor %}
      </p>
      <p class="text-primary fw-bold fs-4">Price: {{ book.price }}€</p>
      <p><strong>Rating:</strong> {{ book.rating }}/10</p>
      <div class="d-flex flex-row justify-content-center mb-5">
          <a class="btn btn-primary btn-sm" href="{% url "book:update" book.id %}">Update Book</a>
          <a class="btn btn-danger btn-sm ms-4" href="{% url "book:delete" book.id %}">Delete Book</a>

          <form action="{% url 'book:addReadLater' %}" method="POST" class="ms-4">
              {% csrf_token %}
              <input type="hidden" name="book_id" value="{{ book.id }}">

              {% if book.id|stringformat:"s" in request.session.read_later %}
                  <button type="submit" class="btn btn-secondary btn-sm">Remove from Read Later</button>
              {% else %}
                  <button type="submit" class="btn btn-success btn-sm">Add to Read Later</button>
              {% endif %}
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Unit 5/FinalProject/library/books/templates/books/book_list.html
{% extends "books/base.html" %} {% load static %} {% block content %}
<div class="container">
  <h2 class="section-title text-center mb-4 mt-4">All Books!</h2>

  <div class="row mb-3">
    <div class="col-md-4 offset-md-4">
      <label for="sort_select">Sort books by:</label>
      <select id="sort_select" class="form-select" onchange="location = this.value;">
        <option value="?sort_by=">-----------</option>  <!-- Default option with no sorting -->
        <option value="?sort_by=price" {% if request.GET.sort_by == 'price' %}selected{% endif %}>Price (Low to High)</option>
        <option value="?sort_by=-price" {% if request.GET.sort_by == '-price' %}selected{% endif %}>Price (High to Low)</option>
        <option value="?sort_by=-publication_date" {% if request.GET.sort_by == '-publication_date' %}selected{% endif %}>Publication Date (Newest First)</option>
        <option value="?sort_by=publication_date" {% if request.GET.sort_by == 'publication_date' %}selected{% endif %}>Publication Date (Oldest First)</option>
        <option value="?sort_by=-rating" {% if request.GET.sort_by == '-rating' %}selected{% endif %}>Rating (Highest to Lowest)</option>
        <option value="?sort_by=rating" {% if request.GET.sort_by == 'rating' %}selected{% endif %}>Rating (Lowest to Highest)</option>
      </select>
    </div>
  </div>

  <div class="row">
    {% for book in books %}
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100 shadow-sm">
        <a
            href="{% url 'book:detail' book.id %}"
            ><img src="{% if book.image %}{{ book.image.url }}{% else %}{% static "books/default.jpg" %}{% endif %}" class="card-img-top" alt="{{ book.title }}" style="height: 200px; object-fit: cover" /></a>
        <div class="card-body">
          <h5 class="card-title">{{ book.title }}</h5>
          <p class="card-text">{{ book.description }}</p>
          <a
            href="{% url 'book:detail' book.id %}"
            class="btn btn-primary btn-sm mb-3"
            >Read more</a
          >
          <p><strong>Written by:
            {% for author in book.authors.all %}
            </strong> <a href="{% url 'book:authors_detail' author.id %}" style="color:black">{{ author.name }}</a>
            {% endfor %}
          </p>
          <p><strong>Price:</strong> {{ book.price }}€</p>
          <p><strong>Rating:</strong> {{ book.rating }}</p>
        </div>
        <div class="card-footer text-muted">
          <small>Published: {{ book.publication_date|date:"j F, Y" }}</small>
        </div>
      </div>
    </div>
    {% endfor %}
    <a class="btn btn-primary btn mb-3" href="{% url "book:add" %}">Add Book</a>
  </div>
</div>
{% endblock %}

Unit 5/FinalProject/library/books/templates/books/book_search.html
{% extends "books/base.html" %} {% block content %}
<div class="container mt-4">
  <h2 class="text-center">Búsqueda de Libros</h2>
  {% if books %}
  <h4 class="mb-4">Resultados para "{{ query }}":</h4>
  <div class="row">
    {% for book in books %}
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100 shadow-sm">
        <img
          src="{{ book.image.url }}"
          class="card-img-top"
          alt="{{ book.title }}"
          style="height: 200px; object-fit: cover"
        />
        <div class="card-body">
          <h5 class="card-title">{{ book.title }}</h5>
          <p class="card-text">{{ book.description|truncatewords:15 }}</p>
          <a
            href="{% url 'book:detail' book.id %}"
            class="btn btn-primary btn-sm"
            >Leer más</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <h4 class="text-muted">No se encontraron libros para "{{ query }}".</h4>
  {% endif %}
</div>
{% endblock %}

Unit 5/FinalProject/library/books/templates/books/delete_book.html
{% extends "books/base.html" %} 
{% load static %} 
{% block content %}

<div class="container d-flex justify-content-center align-items-center" style="min-height:70vh">
  <div class="card shadow p-4 text-center">
    <h2 class="text-danger">Confirm Deletion</h2>
    <h5 class="mt-3">Are you sure you want to delete the book:</h5>
    <h4 class="text-primary fw-bold">{{ book.title }}</h4>
    
    <form action="" method="POST">
      {% csrf_token %}
      {% comment %} <button type="submit" class="btn btn-danger mt-3">Delete</button> {% endcomment %}
      <h3>Oh,oh! :(
        <br>
        You don't have permissions...</h3>
      <a href="{% url 'book:detail' book.id %}" class="btn btn-secondary mt-3">Cancel</a>
    </form>
  </div>
</div>

{% endblock content %}

Unit 5/FinalProject/library/books/templates/books/home.html
{% extends "books/base.html" %} {% load static %} {% block content %}
<div class="container-fluid p-0 position-relative">
  <img
    src="{% static 'books/libros.jpg' %}"
    class="img-fluid w-100 custom-height"
    alt="Bookstore"
  />
  <div class="text-overlay">
    <h1>Welcome to the library!</h1>
    <p>Explore our book collections and find your next favorite.</p>
  </div>
</div>
<div class="container mt-4">
  <h2 class="section-title text-center mb-4">Recommended Books</h2>
  <div class="row">
    {% for book in books %}
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100 shadow-sm">
        <a
            href="{% url 'book:detail' book.id %}"><img src="{% if book.image %}{{ book.image.url }}{% else %}{% static "books/default.jpg" %}{% endif %}" class="card-img-top" alt="{{ book.title }}" style="height: 200px; object-fit: cover" /></a>
        <div class="card-body">
          <h5 class="card-title">{{ book.title }}</h5>
          <p class="card-text">{{ book.description }}</p>
          <a
            href="{% url 'book:detail' book.id %}"
            class="btn btn-primary btn-sm mb-3"
            >Read more</a
            >
            <p><strong>Written by:
            {% for author in book.authors.all %}
            </strong> <a href="{% url 'book:authors_detail' author.id %}" style="color:black">{{ author.name }}</a>
            {% endfor %}
          </p>
            <p><strong>Price:</strong> {{ book.price }}€</p>
            <p><strong>Rating:</strong> {{ book.rating }}</p>
        </div>
        <div class="card-footer text-muted">
          <small>Published: {{ book.publication_date|date:"j F, Y" }}</small>
        </div>
      </div>
    </div>
    {% endfor %}
    <a href="{% url 'book:books' %}" class="btn btn-primary btn mb-3">See all books</a>
  </div>
</div>
{% endblock %}

Unit 5/FinalProject/library/books/templates/books/read_later.html
{% extends "books/base.html" %} 
{% block content %}
{% load static %}
<div class="container">
  <h2 class="section-title text-center mb-4 mt-4"">Read Later List</h2>

  {% if books %}
  <div class="row">
    {% for book in books %}
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100 shadow-sm">
        <a
            href="{% url 'book:detail' book.id %}"><img src="{% if book.image %}{{ book.image.url }}{% else %}{% static "books/default.jpg" %}{% endif %}" class="card-img-top" alt="{{ book.title }}" style="height: 200px; object-fit: cover" /></a>
        <div class="card-body">
          <h5 class="card-title">{{ book.title }}</h5>
          <p class="card-text">{{ book.description }}</p>
          <a
            href="{% url 'book:detail' book.id %}"
            class="btn btn-primary btn-sm mb-3"
            >Read more</a
            >
            <p><strong>Written by:
            {% for author in book.authors.all %}
            </strong> <a href="{% url 'book:authors_detail' author.id %}" style="color:black">{{ author.name }}</a>
            {% endfor %}
          </p>
            <p><strong>Price:</strong> {{ book.price }}€</p>
            <p><strong>Rating:</strong> {{ book.rating }}</p>
        </div>
        <div class="card-footer text-muted">
          <small>Published: {{ book.publication_date|date:"j F, Y" }}</small>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p class="text-center">No books saved in Read Later.</p>
  {% endif %}
</div>
{% endblock %}

Unit 5/FinalProject/library/books/templates/books/search.html
{% extends "books/base.html" %} {% block content %}{% load static %}
<div class="container mt-4">
  <h2 class="text-center">Library Search</h2>

  <form method="GET" action="{% url 'book:search' %}" class="mb-3">
    <div class="input-group">
      <input
        type="text"
        name="q"
        value="{{ query }}"
        class="form-control"
        placeholder="Search books or authors..."
      />
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  </form>

  <div class="mb-4 text-center">
    <a
      href="{% url 'book:search' %}?q={{ query }}&filter=all"
      class="btn btn-outline-primary {% if filter == 'all' %}active{% endif %}"
      >All</a
    >
    <a
      href="{% url 'book:search' %}?q={{ query }}&filter=books"
      class="btn btn-outline-secondary {% if filter == 'books' %}active{% endif %}"
      >Books</a
    >
    <a
      href="{% url 'book:search' %}?q={{ query }}&filter=authors"
      class="btn btn-outline-secondary {% if filter == 'authors' %}active{% endif %}"
      >Authors</a
    >
  </div>

  {% if books or authors %}
  <h4 class="mb-4">Results for "{{ query }}":</h4>

  {% if books and filter != "authors" %}
  <h3 class="mt-4">Books:</h3>
  <div class="row">
    {% for book in books %}
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100 shadow-sm">
        <a
            href="{% url 'book:detail' book.id %}"
            ><img src="{% if book.image %}{{ book.image.url }}{% else %}{% static "books/default.jpg" %}{% endif %}" class="card-img-top" alt="{{ book.title }}" style="height: 200px; object-fit: cover" /></a>
        <div class="card-body">
          <h5 class="card-title">{{ book.title }}</h5>
          <p class="card-text">{{ book.description }}</p>
          <a
            href="{% url 'book:detail' book.id %}"
            class="btn btn-primary btn-sm mb-3"
            >Read more</a
          >
          <p><strong>Written by:
            {% for author in book.authors.all %}
            </strong> <a href="{% url 'book:authors_detail' author.id %}" style="color:black">{{ author.name }}</a>
            {% endfor %}
          </p>
          <p><strong>Price:</strong> {{ book.price }}€</p>
          <p><strong>Rating:</strong> {{ book.rating }}</p>
        </div>
        <div class="card-footer text-muted">
          <small>Published: {{ book.publication_date|date:"j F, Y" }}</small>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %} {% if authors and filter != "books" %}
  <h3 class="mt-4">Authors:</h3>
  <div class="row">
    {% for author in authors %}
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100 shadow-sm">
        <a
            href="{% url 'book:authors_detail' author.id %}"><img
          src="{% if author.image %}{{ author.image.url }}{% else %}{% static 'authors/predeterminado.jpg' %}{% endif %}"
          class="card-img-top"
          alt="{{ author.name }}"
          style="height: 200px; object-fit: cover"
        /></a>
        <div class="card-body">
          <h5 class="card-title">{{ author.name }}</h5>
          <p class="card-text">{{ author.bio }}</p>
          <a
            href="{% url 'book:authors_detail' author.id %}"
            class="btn btn-primary btn-sm mb-3"
            >Learn more</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %} {% else %}
  <h4 class="text-muted">No results found for "{{ query }}".</h4>
  {% endif %}
</div>
{% endblock %}

Unit 5/FinalProject/library/books/templates/books/update_book.html
{% extends "books/base.html" %} {% load static %}{% block content %}
<div class="container d-flex justify-content-center align-items-center text-center mt-4 mb-4">
  <div class="card shadow p-4 w-50">
    <h2 class="text-center mb-4">Update: {{ book.title }}</h2>
    <form action="" method="POST" enctype="multipart/form-data">
      {% comment %} {% csrf_token %}
      {% for field in form %}
        <div class="mb-3">
          {{ field.label_tag }}
          {{ field }}
          <div class="text-danger">
            {{ field.errors }}
          </div>
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary w-100">Update Book</button> {% endcomment %}
      <h3>Oh,oh! :(
        <br>
        You don't have permissions...</h3>
      <a href="{% url 'book:detail' book.id %}" class="btn btn-secondary w-100 mt-3">Cancel</a>
    </form>
  </div>
</div>
{% endblock content %}